#!/bin/sh
##########################################
# Check-in an Alfresco document via Nautilus.
# 2011/04/15
# Nicolas Raoul - Aegif
##########################################
# Instructions:
# Place this script in your ~/.gnome2/nautilus-scripts
# Below, change "admin" to your Alfresco password:
PASSWORD="admin"
# Now Nautilus' context menu should have the Alfresco actions.
##########################################
# TODO
# - Show graphical feedback in case of error
# - Get password from Nautilus, or at least from the Check-out script
##########################################

#URI=${NAUTILUS_SCRIPT_SELECTED_URIS}
URI="dav://admin@localhost:8080/alfresco/webdav/User%20Homes/leo/test.txt%20(Working%20Copy)"

# If the user has clicked on the private working copy, get URI of original file instead
URI=$(echo $URI | sed -e "s/%20(Working%20Copy)//g")

# Extract username and server
USERNAME=$(echo $URI | sed -e "s/dav:\/\///g" -e "s/@.*//g")
SERVER=$(echo $URI | sed -e "s/.*@//g" -e "s/\/.*//g")

# Build Alfresco CMIS URL from Alfresco WebDAV URI
URL=$(echo $URI | sed -e "s/.*alfresco\/webdav\///g")
URL="http://$SERVER/alfresco/s/cmis/p/$URL"
echo "Alfresco CMIS URL: $URL"
TMPDIR=$(mktemp -d AlfrescoLinuxMacCheckInOut-XXXXX)
echo "TMPDIR=$TMPDIR"
curl -u$USERNAME:$PASSWORD "$URL" > $TMPDIR/output
NODEREF=$(grep "<link rel=\"working-copy\"" $TMPDIR/output | sed -e "s/.*s\/cmis\/pwc\/s\///g" -e "s/\".*//g" -e "s/workspace:/workspace:\/\//g" -e "s/i\///g")
echo "Alfresco Noderef: $NODEREF"
# Example: "workspace://SpacesStore/ebc57ec5-e817-4aa4-9217-936b3f355048"
exit

echo "<?xml version=\"1.0\" encoding=\"utf-8\"?>
<entry xmlns=\"http://www.w3.org/2005/Atom\" xmlns:cmisra=\"http://docs.oasis-open.org/ns/cmis/restatom/200908/\" xmlns:cmis=\"http://docs.oasis-open.org/ns/cmis/core/200908/\">
<cmisra:object>
<cmis:properties>
<cmis:propertyId propertyDefinitionId=\"cmis:objectId\">
<cmis:value>${NODEREF}</cmis:value>
</cmis:propertyId>
</cmis:properties>
</cmisra:object>
</entry>
" > $TMPDIR/atomentry.xml

curl -X PUT -u$USERNAME:$PASSWORD "http://$SERVER/alfresco/s/cmis/checkedout" -H "Content-Type:application/atom+xml;type=entry;charset=UTF-8" -d @$TMPDIR/atomentry.xml > $TMPDIR/checkout-result.xml

rm -rf $TMPDIR
echo "Done"
